name: Run tests

on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Ensure files are formatted with black
        run: |
          pip install --upgrade pip
          pip install black
          black --check tests.py

  run-test:
    needs: [black]
    runs-on: ubuntu-latest
    container: tensorflow/tensorflow
    steps:
      - uses: actions/checkout@v2
      - run: |
          apt install -y tar
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install gdown==4.3.1
          gdown --id 1-5OxB8eQTkiE7HStTkk4sOsdixKKQxsq
          tar -xvf "heart_test_data.tar" "heart_test_data"
          rm -rf heart_test_data.tar
          sh scripts/test.sh
